#Building Stage 
FROM node:20.11.1-alpine AS builder

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . /app/

RUN yarn build 

# Production Stage

FROM node:20.11.1-alpine 

WORKDIR /app

COPY --from=builder /app/build ./build

RUN yarn global add serve && yarn cache clean

EXPOSE 3000

RUN addgroup -S app && adduser -S app -G app

USER app

CMD ["serve", "-s", "build", "-l", "3000"]
